FROM solr:9

USER root

RUN mkdir -p /opt/solr/server/solr/configsets/drupal/conf

COPY solr-config/ /opt/solr/server/solr/configsets/drupal/conf/

RUN chown -R solr:solr /opt/solr/server/solr/configsets/drupal

USER solr
